dist: xenial   # required for Python >= 3.7
language: python
python:
  - "3.7"
install: pip install -r requirements.txt
script: python corgis.py wind-turbines python
deploy:
  provider: pages
  local_dir: website
  verbose: true
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  keep_history: false
  on:
    branch: master
